version: '3.7'

services:
  postgresql:
    image: postgres:16.0
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRES_PASSWORD=/run/secrets/pg_password
      - POSTGRES_USER=demo-user
      - POSTGRESQL_DATABASE=postgres
    ports:
      - '5432:5432'
  app:
    image: mirjalalhashimli/demo
    environment:
      - DB_USER=demo-user
      - DB_PASS=/run/secrets/pg_password
      - DB_NAME=postgres
    ports:
      - '80:8080'
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local

secrets:
  pg_password:
    external: true
